Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,14 +18,23 @@ jobs:
         with:
           python-version: '3.x'  # Specify the Python version you need
 
+      - name: Check if requirements.txt exists
+        run: test -f requirements.txt || echo "::error::requirements.txt not found"
+        
+      - name: Install Dependencies
+        if: success()
+        run: |
+          python -m pip install --upgrade pip
+          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
+
       - name: Run Tests with pytest
         run: |
-          pytest -v --junitxml=report.xml --html=report.html
+          /Users/nour/Documents/GitHub/pytestExample/venv/bin/pytest -v --junitxml=report.xml --html=report.html
 
       - name: Upload Test Reports
         uses: actions/upload-artifact@v2
         with:
           name: test-reports
           path: |
-            results/report.xml
-            results/report.html
+            report.xml
+            report.html
